version: 0.2

phases:
 install:
  runtime-versions:
   docker: 18
 pre_build:
  commands:
   - $(aws ecr get-login --no-include-email --region us-east-1)
 build:
  commands:
   - cd PensionEurekaServer
   - mvn compile
   - mvn package
   - docker build -t pension/eurekaserver .
   - docker tag pension/eurekaserver 885843804602.dkr.ecr.us-east-1.amazonaws.com/eureka-server:latest
 post_build:
  commands:
   - docker push 885843804602.dkr.ecr.us-east-1.amazonaws.com/eureka-server:latest
   - printf '[{"name":"eureka-container","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-1.amazonaws.com/eureka-server:latest > taskdefinition.json
artifacts:
 files:
  - PensionEurekaServer/taskdefinition.json
