version: 0.2

phases:
 install:
  runtime-versions:
   docker: 18
 pre_build:
  commands:
   - $(aws ecr get-login --no-include-email --region us-east-1)
 build:
  commands:
   - cd PensionGateway
   - mvn compile
   - mvn package
   - docker build -t pension/gateway .
   - docker tag pension/gateway 885843804602.dkr.ecr.us-east-1.amazonaws.com/eureka-gateway:latest
 post_build:
  commands:
   - docker push 885843804602.dkr.ecr.us-east-1.amazonaws.com/eureka-gateway:latest
   - printf '[{"name":"gateway-container","imageUri":"%s"}]' 885843804602.dkr.ecr.us-east-1.amazonaws.com/eureka-gateway:latest > taskdefinition.json
artifacts:
 files:
  - PensionGateway/taskdefinition.json
