server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
      - id: process-pension-service
        uri: http://localhost:8084
        predicates:
        - Path=/process/**
      - id: auth-service
        uri: http://localhost:8081
        predicates:
        - Path=/auth/**
      - id: pensioner-details-service
        uri: http://localhost:8082
        predicates:
        - Path=/**
      - id: pensioner-disbursement-service
        uri: http://localhost:8083
        predicates:
        - Path=/**
      