server:
  port: 8090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: http://44.192.27.247:8081
        predicates:
          - Path=/auth/**
      - id: process-pension-service
        uri: http://3.215.22.61:8084
        predicates:
          - Path=/process/**
      - id: pensioner-details-service
        uri: http://3.235.225.18:8082
        predicates:
          - Path=/details/**
      - id: pensioner-disbursement-service
        uri: http://35.175.136.40:8083
        predicates:
          - Path=/disburse/**
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://3.239.0.202:8761/eureka/
