server:
  port: 8090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: http://localhost:8081
        predicates:
          - Path=/auth/**
      - id: process-pension-service
        uri: http://localhost:8084
        predicates:
          - Path=/process/**
      - id: pensioner-details-service
        uri: http://localhost:8082
        predicates:
          - Path=/details/**
      - id: pensioner-disbursement-service
        uri: http://localhost:8083
        predicates:
          - Path=/disburse/**
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
